import type { PRAnalysis, DiffLine, DiffHunk, FileDiff } from './types';

// ── Line helpers ─────────────────────────────────────────────────────────────
const a = (c: string): DiffLine => ({ type: 'add', content: c });
const d = (c: string): DiffLine => ({ type: 'del', content: c });
const x = (c: string): DiffLine => ({ type: 'ctx', content: c });
const h = (c: string): DiffLine => ({ type: 'hdr', content: c });

// ── FILE DIFFS ────────────────────────────────────────────────────────────────

const authConfigDiff: FileDiff = {
  path: 'src/config/auth.config.ts',
  additions: 16,
  deletions: 4,
  hunks: [
    {
      header: '@@ -1,14 +1,26 @@',
      lines: [
        x("import { SignOptions } from 'jsonwebtoken';"),
        x(''),
        x('export const AUTH_CONFIG = {'),
        d("  accessTokenSecret: process.env.JWT_SECRET!,"),
        d("  accessTokenExpiry: '7d',"),
        d("  refreshTokenExpiry: undefined,"),
        a("  accessTokenSecret: process.env.JWT_ACCESS_SECRET!,"),
        a("  refreshTokenSecret: process.env.JWT_REFRESH_SECRET!,"),
        a("  accessTokenExpiry: '30d',"),
        a("  refreshTokenExpiry: '90d',"),
        x("  algorithm: 'HS256' as SignOptions['algorithm'],"),
        x('};'),
        x(''),
        a('export interface TokenPair {'),
        a('  accessToken: string;'),
        a('  refreshToken: string;'),
        a('  expiresIn: number;'),
        a('}'),
        a(''),
        a('export interface RefreshTokenPayload {'),
        a('  sub: string;'),
        a('  sessionId: string;'),
        a('  family: string;'),
        a('  iat: number;'),
        a('  exp: number;'),
        a('}'),
      ],
    },
    {
      header: '@@ -16,6 +28,11 @@',
      lines: [
        x('export const ACCESS_TOKEN_OPTIONS: SignOptions = {'),
        x('  expiresIn: AUTH_CONFIG.accessTokenExpiry,'),
        x('  algorithm: AUTH_CONFIG.algorithm,'),
        x('};'),
        x(''),
        a('export const REFRESH_TOKEN_OPTIONS: SignOptions = {'),
        a('  expiresIn: AUTH_CONFIG.refreshTokenExpiry,'),
        a('  algorithm: AUTH_CONFIG.algorithm,'),
        a('};'),
      ],
    },
  ],
};

const middlewareDiff: FileDiff = {
  path: 'src/middleware/authenticate.ts',
  additions: 38,
  deletions: 11,
  hunks: [
    {
      header: '@@ -1,8 +1,10 @@',
      lines: [
        x("import { Request, Response, NextFunction } from 'express';"),
        d("import jwt from 'jsonwebtoken';"),
        d("import { AUTH_CONFIG } from '../config/auth.config';"),
        a("import jwt, { TokenExpiredError, JsonWebTokenError } from 'jsonwebtoken';"),
        a("import { AUTH_CONFIG, RefreshTokenPayload } from '../config/auth.config';"),
        a("import { generateAccessToken } from '../services/auth.service';"),
        a("import { Session } from '../models/Session';"),
        x(''),
        x('declare global {'),
        x('  namespace Express {'),
        x('    interface Request { user?: { id: string; sessionId?: string } }'),
        x('  }'),
        x('}'),
      ],
    },
    {
      header: '@@ -12,22 +14,48 @@',
      lines: [
        x('export async function authenticate('),
        x('  req: Request,'),
        x('  res: Response,'),
        x('  next: NextFunction,'),
        x('): Promise<void> {'),
        x("  const token = req.headers.authorization?.split(' ')[1];"),
        x(''),
        x('  if (!token) {'),
        x("    res.status(401).json({ error: 'No token provided' });"),
        x('    return;'),
        x('  }'),
        x(''),
        x('  try {'),
        d("    const payload = jwt.verify(token, AUTH_CONFIG.accessTokenSecret);"),
        d("    req.user = { id: payload.sub as string };"),
        d("    next();"),
        a("    const payload = jwt.verify("),
        a("      token,"),
        a("      AUTH_CONFIG.accessTokenSecret,"),
        a("    ) as jwt.JwtPayload;"),
        a("    req.user = { id: payload.sub as string, sessionId: payload.sid };"),
        a("    next();"),
        x('  } catch (error) {'),
        d("    res.status(401).json({ error: 'Invalid or expired token' });"),
        a("    if (error instanceof TokenExpiredError) {"),
        a("      res.status(401).json({"),
        a("        error: 'TOKEN_EXPIRED',"),
        a("        code: 'REFRESH_REQUIRED',"),
        a("        message: 'Access token has expired. Use refresh token to renew.',"),
        a("      });"),
        a("      return;"),
        a("    }"),
        a("    if (error instanceof JsonWebTokenError) {"),
        a("      res.status(401).json({ error: 'INVALID_TOKEN', message: 'Malformed token.' });"),
        a("      return;"),
        a("    }"),
        a("    next(error);"),
        x('  }'),
        x('}'),
      ],
    },
  ],
};

// ── SPLIT-BRAIN: src/routes/auth.routes.ts ───────────────────────────────────
// Hunk 0-1 belong to Intent: Auth Token Upgrade
// Hunk 2-3 belong to Intent: Session Persistence
const authRoutesDiff: FileDiff = {
  path: 'src/routes/auth.routes.ts',
  additions: 63,
  deletions: 9,
  hunks: [
    // ── HUNK 0 (Auth intent) ──────────────────
    {
      header: '@@ -1,12 +1,14 @@',
      lines: [
        x("import { Router } from 'express';"),
        x("import { body, validationResult } from 'express-validator';"),
        d("import { generateToken } from '../services/auth.service';"),
        a("import { generateTokenPair, rotateRefreshToken, revokeSession } from '../services/auth.service';"),
        x("import { UserRepository } from '../repositories/user.repository';"),
        a("import { SessionRepository } from '../repositories/session.repository';"),
        x("import bcrypt from 'bcryptjs';"),
        x(''),
        x('const router = Router();'),
        x('const userRepo = new UserRepository();'),
        a('const sessionRepo = new SessionRepository();'),
      ],
    },
    // ── HUNK 1 (Auth intent) ──────────────────
    {
      header: '@@ -28,12 +31,35 @@',
      lines: [
        x("router.post('/login', ["),
        x("  body('email').isEmail().normalizeEmail(),"),
        x("  body('password').isLength({ min: 8 }),"),
        x('], async (req, res) => {'),
        x('  const errors = validationResult(req);'),
        x("  if (!errors.isEmpty()) return res.status(422).json({ errors: errors.array() });"),
        x(''),
        x('  const { email, password } = req.body;'),
        x('  const user = await userRepo.findByEmail(email);'),
        x("  if (!user || !await bcrypt.compare(password, user.passwordHash)) {"),
        x("    return res.status(401).json({ error: 'INVALID_CREDENTIALS' });"),
        x('  }'),
        x(''),
        d("  const token = generateToken({ sub: user.id });"),
        d("  res.json({ token, user: { id: user.id, email: user.email } });"),
        a("  const { accessToken, refreshToken, expiresIn } = await generateTokenPair(user.id);"),
        a("  res.json({ accessToken, refreshToken, expiresIn, user: { id: user.id, email: user.email } });"),
        x('});'),
        x(''),
        a("router.post('/refresh', async (req, res) => {"),
        a("  const { refreshToken } = req.body;"),
        a("  if (!refreshToken) return res.status(400).json({ error: 'MISSING_REFRESH_TOKEN' });"),
        a("  try {"),
        a("    const tokens = await rotateRefreshToken(refreshToken);"),
        a("    res.json(tokens);"),
        a("  } catch (err) {"),
        a("    res.status(401).json({ error: 'INVALID_REFRESH_TOKEN' });"),
        a("  }"),
        a("});"),
      ],
    },
    // ── HUNK 2 (Session persistence intent) ──────────────────
    {
      header: '@@ -42,6 +68,20 @@',
      lines: [
        x("router.post('/logout', authenticate, async (req, res) => {"),
        d("  res.json({ message: 'Logged out successfully' });"),
        a("  try {"),
        a("    await revokeSession(req.user!.sessionId!);"),
        a("    await sessionRepo.deleteByUserId(req.user!.id);"),
        a("    res.json({ message: 'Session revoked and user logged out.' });"),
        a("  } catch {"),
        a("    res.status(500).json({ error: 'SESSION_REVOKE_FAILED' });"),
        a("  }"),
        x('});'),
      ],
    },
    // ── HUNK 3 (Session persistence intent) ──────────────────
    {
      header: '@@ -50,5 +80,18 @@',
      lines: [
        a("router.get('/sessions', authenticate, async (req, res) => {"),
        a("  const sessions = await sessionRepo.findActiveByUserId(req.user!.id);"),
        a("  res.json({"),
        a("    sessions: sessions.map(s => ({"),
        a("      id: s.id,"),
        a("      deviceInfo: s.deviceInfo,"),
        a("      createdAt: s.createdAt,"),
        a("      expiresAt: s.expiresAt,"),
        a("      isCurrent: s.id === req.user!.sessionId,"),
        a("    })),"),
        a("  });"),
        a("});"),
        x(''),
        x('export default router;'),
      ],
    },
  ],
};

const loginFormDiff: FileDiff = {
  path: 'src/components/auth/LoginForm.tsx',
  additions: 67,
  deletions: 18,
  isNew: false,
  hunks: [
    {
      header: "@@ -1,10 +1,14 @@",
      lines: [
        d("import React, { useState } from 'react';"),
        a("import React, { useState, useTransition } from 'react';"),
        x("import { Button } from '../ui/Button';"),
        a("import { AlertCircle, Loader2, LogIn } from 'lucide-react';"),
        a("import styles from '../../styles/auth.module.css';"),
        x(''),
        d("interface LoginFormProps { onSuccess: (token: string) => void }"),
        a("interface LoginFormProps {"),
        a("  onSuccess: (token: string, refreshToken: string) => void;"),
        a("  redirectTo?: string;"),
        a("}"),
      ],
    },
    {
      header: '@@ -12,38 +16,68 @@',
      lines: [
        x('export function LoginForm({ onSuccess }: LoginFormProps) {'),
        x("  const [email, setEmail] = useState('');"),
        x("  const [password, setPassword] = useState('');"),
        d("  const [error, setError] = useState('');"),
        d("  const [loading, setLoading] = useState(false);"),
        a("  const [error, setError] = useState<string | null>(null);"),
        a("  const [isPending, startTransition] = useTransition();"),
        a("  const [rememberMe, setRememberMe] = useState(false);"),
        x(''),
        x('  const handleSubmit = async (e: React.FormEvent) => {'),
        x('    e.preventDefault();'),
        d("    setLoading(true);"),
        d("    setError('');"),
        d("    const res = await fetch('/api/auth/login', {"),
        d("      method: 'POST',"),
        d("      body: JSON.stringify({ email, password }),"),
        d("    });"),
        d("    const data = await res.json();"),
        d("    if (!res.ok) { setError(data.error); setLoading(false); return; }"),
        d("    onSuccess(data.token);"),
        a("    setError(null);"),
        a("    startTransition(async () => {"),
        a("      const res = await fetch('/api/auth/login', {"),
        a("        method: 'POST',"),
        a("        headers: { 'Content-Type': 'application/json' },"),
        a("        body: JSON.stringify({ email, password, rememberMe }),"),
        a("      });"),
        a("      const data = await res.json();"),
        a("      if (!res.ok) {"),
        a("        setError(data.message ?? 'Authentication failed. Please try again.');"),
        a("        return;"),
        a("      }"),
        a("      onSuccess(data.accessToken, data.refreshToken);"),
        a("    });"),
        x('  };'),
        x(''),
        x('  return ('),
        d("    <div className='login-container'>"),
        d("      <h2>Sign In</h2>"),
        d("      {error && <p className='error'>{error}</p>}"),
        a("    <div className={styles.container}>"),
        a("      <div className={styles.header}>"),
        a("        <LogIn className='w-6 h-6 text-indigo-400' />"),
        a("        <h2 className={styles.title}>Welcome back</h2>"),
        a("        <p className={styles.subtitle}>Sign in to your account</p>"),
        a("      </div>"),
        a("      {error && ("),
        a("        <div className={styles.errorBanner}>"),
        a("          <AlertCircle className='w-4 h-4 flex-shrink-0' />"),
        a("          <span>{error}</span>"),
        a("        </div>"),
        a("      )}"),
      ],
    },
    {
      header: '@@ -52,9 +84,16 @@',
      lines: [
        d("      <button type='submit' disabled={loading}>"),
        d("        {loading ? 'Signing in...' : 'Sign In'}"),
        d("      </button>"),
        a("      <label className={styles.checkboxRow}>"),
        a("        <input type='checkbox' checked={rememberMe} onChange={e => setRememberMe(e.target.checked)} />"),
        a("        <span>Keep me signed in for 30 days</span>"),
        a("      </label>"),
        a("      <Button type='submit' size='lg' className='w-full' disabled={isPending}>"),
        a("        {isPending ? <Loader2 className='w-4 h-4 animate-spin mr-2' /> : null}"),
        a("        {isPending ? 'Authenticating...' : 'Sign In'}"),
        a("      </Button>"),
        x('    </div>'),
        x('  );'),
        x('}'),
      ],
    },
  ],
};

const buttonDiff: FileDiff = {
  path: 'src/components/ui/Button.tsx',
  additions: 29,
  deletions: 7,
  hunks: [
    {
      header: '@@ -1,24 +1,46 @@',
      lines: [
        x("import React from 'react';"),
        x("import { clsx } from 'clsx';"),
        x(''),
        d("type Variant = 'primary' | 'secondary';"),
        d("type Size = 'md';"),
        a("type Variant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'success';"),
        a("type Size = 'sm' | 'md' | 'lg' | 'icon';"),
        x(''),
        x('interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {'),
        x('  variant?: Variant;'),
        x('  size?: Size;'),
        a('  loading?: boolean;'),
        a('  leftIcon?: React.ReactNode;'),
        x('}'),
        x(''),
        d("const variantStyles: Record<Variant, string> = {"),
        d("  primary: 'bg-indigo-600 text-white hover:bg-indigo-500',"),
        d("  secondary: 'bg-gray-700 text-white hover:bg-gray-600',"),
        d("};"),
        a("const variantStyles: Record<Variant, string> = {"),
        a("  primary: 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-sm shadow-indigo-900/40',"),
        a("  secondary: 'bg-[#1c1c30] hover:bg-[#252540] text-[#c0c0e0] border border-[#262640]',"),
        a("  ghost: 'bg-transparent hover:bg-white/5 text-[#9090b0] hover:text-[#f0f0f8]',"),
        a("  danger: 'bg-red-950/60 hover:bg-red-900/70 text-red-300 border border-red-900/50',"),
        a("  success: 'bg-emerald-950/60 hover:bg-emerald-900/60 text-emerald-300 border border-emerald-900/50',"),
        a("};"),
        a(""),
        a("const sizeStyles: Record<Size, string> = {"),
        a("  sm: 'h-7 px-2.5 text-xs rounded-md gap-1.5',"),
        a("  md: 'h-9 px-3.5 text-sm rounded-lg gap-2',"),
        a("  lg: 'h-10 px-4 text-sm rounded-lg gap-2',"),
        a("  icon: 'h-8 w-8 rounded-md',"),
        a("};"),
        x(''),
        d("export function Button({ variant = 'primary', size = 'md', className, children, ...props }: ButtonProps) {"),
        d("  return ("),
        d("    <button className={clsx(variantStyles[variant], className)} {...props}>"),
        d("      {children}"),
        d("    </button>"),
        d("  );"),
        d("}"),
        a("export function Button({ variant = 'primary', size = 'md', loading, leftIcon, className, children, disabled, ...props }: ButtonProps) {"),
        a("  return ("),
        a("    <button"),
        a("      className={clsx("),
        a("        'inline-flex items-center justify-center font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500/60 disabled:opacity-50 disabled:pointer-events-none',"),
        a("        variantStyles[variant],"),
        a("        sizeStyles[size],"),
        a("        className,"),
        a("      )}"),
        a("      disabled={disabled || loading}"),
        a("      {...props}"),
        a("    >"),
        a("      {loading ? <span className='w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin' /> : leftIcon}"),
        a("      {children}"),
        a("    </button>"),
        a("  );"),
        a("}"),
      ],
    },
  ],
};

const authCssDiff: FileDiff = {
  path: 'src/styles/auth.module.css',
  additions: 42,
  deletions: 3,
  hunks: [
    {
      header: '@@ -1,8 +1,47 @@',
      lines: [
        d('.login-container { padding: 24px; background: #fff; border-radius: 8px; }'),
        d('.error { color: red; margin-bottom: 8px; }'),
        a('@keyframes fadeInUp {'),
        a('  from { opacity: 0; transform: translateY(16px); }'),
        a('  to   { opacity: 1; transform: translateY(0); }'),
        a('}'),
        a('@keyframes shake {'),
        a('  0%, 100% { transform: translateX(0); }'),
        a('  20%, 60% { transform: translateX(-6px); }'),
        a('  40%, 80% { transform: translateX(6px); }'),
        a('}'),
        a(''),
        a('.container {'),
        a('  animation: fadeInUp 0.35s ease-out;'),
        a('  background: #0f0f1a;'),
        a('  border: 1px solid #1c1c30;'),
        a('  border-radius: 16px;'),
        a('  padding: 32px;'),
        a('  width: 100%;'),
        a('  max-width: 400px;'),
        a('}'),
        a('.header { display: flex; flex-direction: column; align-items: center; gap: 8px; margin-bottom: 28px; }'),
        a('.title { font-size: 22px; font-weight: 700; color: #f0f0f8; }'),
        a('.subtitle { font-size: 14px; color: #9090b0; }'),
        a('.errorBanner {'),
        a('  display: flex; align-items: center; gap: 8px;'),
        a('  background: rgba(239,68,68,0.1); border: 1px solid rgba(239,68,68,0.3);'),
        a('  border-radius: 8px; padding: 10px 12px; color: #f87171;'),
        a('  font-size: 13px; margin-bottom: 16px;'),
        a('  animation: shake 0.4s ease-out;'),
        a('}'),
        a('.checkboxRow {'),
        a('  display: flex; align-items: center; gap: 8px;'),
        a('  font-size: 13px; color: #9090b0; cursor: pointer;'),
        a('  margin-bottom: 12px;'),
        a('}'),
        a('.checkboxRow input[type="checkbox"] {'),
        a('  accent-color: #6366f1; width: 14px; height: 14px;'),
        a('}'),
      ],
    },
  ],
};

const sessionMigrationDiff: FileDiff = {
  path: 'db/migrations/20240615_create_sessions.sql',
  additions: 26,
  deletions: 0,
  isNew: true,
  hunks: [
    {
      header: '@@ -0,0 +1,26 @@',
      lines: [
        a('-- Migration: 20240615_create_sessions'),
        a('-- Creates persistent session storage for OAuth2 refresh token tracking'),
        a(''),
        a('CREATE TABLE IF NOT EXISTS user_sessions ('),
        a('  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),'),
        a('  user_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,'),
        a('  refresh_token_hash TEXT   NOT NULL UNIQUE,'),
        a("  token_family  UUID        NOT NULL DEFAULT gen_random_uuid(), -- detects reuse attacks"),
        a('  device_info   JSONB,'),
        a('  ip_address    INET,'),
        a('  user_agent    TEXT,'),
        a('  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),'),
        a('  last_used_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),'),
        a('  expires_at    TIMESTAMPTZ NOT NULL,'),
        a('  revoked_at    TIMESTAMPTZ'),
        a(');'),
        a(''),
        a('CREATE INDEX idx_sessions_user_id     ON user_sessions (user_id);'),
        a('CREATE INDEX idx_sessions_token_hash  ON user_sessions (refresh_token_hash);'),
        a('CREATE INDEX idx_sessions_family      ON user_sessions (token_family);'),
        a('CREATE INDEX idx_sessions_expires     ON user_sessions (expires_at) WHERE revoked_at IS NULL;'),
        a(''),
        a("COMMENT ON TABLE user_sessions IS 'Active OAuth2 refresh token sessions per user device.';"),
      ],
    },
  ],
};

const sessionModelDiff: FileDiff = {
  path: 'src/models/Session.ts',
  additions: 72,
  deletions: 0,
  isNew: true,
  hunks: [
    {
      header: '@@ -0,0 +1,72 @@',
      lines: [
        a("import { db } from '../lib/database';"),
        a("import crypto from 'crypto';"),
        a(''),
        a('export interface SessionRow {'),
        a('  id: string;'),
        a('  userId: string;'),
        a('  refreshTokenHash: string;'),
        a('  tokenFamily: string;'),
        a('  deviceInfo: Record<string, string> | null;'),
        a('  ipAddress: string | null;'),
        a('  createdAt: Date;'),
        a('  lastUsedAt: Date;'),
        a('  expiresAt: Date;'),
        a('  revokedAt: Date | null;'),
        a('}'),
        a(''),
        a('export class Session {'),
        a('  static hash(token: string): string {'),
        a("    return crypto.createHash('sha256').update(token).digest('hex');"),
        a('  }'),
        a(''),
        a('  static async create(params: {'),
        a('    userId: string;'),
        a('    refreshToken: string;'),
        a('    deviceInfo?: Record<string, string>;'),
        a('    ipAddress?: string;'),
        a('    expiresAt: Date;'),
        a('  }): Promise<SessionRow> {'),
        a('    const [row] = await db'),
        a("      .insertInto('user_sessions')"),
        a('      .values({'),
        a('        user_id: params.userId,'),
        a('        refresh_token_hash: Session.hash(params.refreshToken),'),
        a('        device_info: params.deviceInfo ?? null,'),
        a('        ip_address: params.ipAddress ?? null,'),
        a('        expires_at: params.expiresAt,'),
        a('      })'),
        a('      .returningAll()'),
        a('      .execute();'),
        a('    return row as SessionRow;'),
        a('  }'),
        a(''),
        a('  static async findByToken(token: string): Promise<SessionRow | null> {'),
        a('    const hash = Session.hash(token);'),
        a('    return db'),
        a("      .selectFrom('user_sessions')"),
        a("      .selectAll()"),
        a("      .where('refresh_token_hash', '=', hash)"),
        a("      .where('revoked_at', 'is', null)"),
        a("      .where('expires_at', '>', new Date())"),
        a('      .executeTakeFirst() ?? null;'),
        a('  }'),
        a(''),
        a('  static async revoke(sessionId: string): Promise<void> {'),
        a('    await db'),
        a("      .updateTable('user_sessions')"),
        a("      .set({ revoked_at: new Date() })"),
        a("      .where('id', '=', sessionId)"),
        a('      .execute();'),
        a('  }'),
        a(''),
        a('  static async revokeFamily(tokenFamily: string): Promise<void> {'),
        a("    // Revoke all tokens in the family on reuse detection"),
        a('    await db'),
        a("      .updateTable('user_sessions')"),
        a("      .set({ revoked_at: new Date() })"),
        a("      .where('token_family', '=', tokenFamily)"),
        a('      .execute();'),
        a('  }'),
        a('}'),
      ],
    },
  ],
};

const authTestDiff: FileDiff = {
  path: 'tests/auth.integration.test.ts',
  additions: 94,
  deletions: 0,
  isNew: true,
  hunks: [
    {
      header: '@@ -0,0 +1,94 @@',
      lines: [
        a("import { describe, it, expect, beforeAll, afterAll } from 'vitest';"),
        a("import request from 'supertest';"),
        a("import { app } from '../src/app';"),
        a("import { db } from '../src/lib/database';"),
        a("import { createTestUser, cleanupTestData } from './helpers';"),
        a(''),
        a("describe('Auth — Refresh Token Flow', () => {"),
        a('  let testUser: { id: string; email: string; password: string };'),
        a('  let accessToken: string;'),
        a('  let refreshToken: string;'),
        a(''),
        a('  beforeAll(async () => {'),
        a("    testUser = await createTestUser({ email: 'refresh@test.com', password: 'Sup3rS3cur3!' });"),
        a('  });'),
        a('  afterAll(() => cleanupTestData(testUser.id));'),
        a(''),
        a("  it('POST /auth/login returns tokenPair with 30d access expiry', async () => {"),
        a("    const res = await request(app).post('/auth/login').send({"),
        a('      email: testUser.email, password: testUser.password,'),
        a('    });'),
        a('    expect(res.status).toBe(200);'),
        a("    expect(res.body).toHaveProperty('accessToken');"),
        a("    expect(res.body).toHaveProperty('refreshToken');"),
        a('    expect(res.body.expiresIn).toBeGreaterThan(25 * 24 * 3600);'),
        a('    accessToken = res.body.accessToken;'),
        a('    refreshToken = res.body.refreshToken;'),
        a('  });'),
        a(''),
        a("  it('POST /auth/refresh rotates token and returns new pair', async () => {"),
        a("    const res = await request(app).post('/auth/refresh').send({ refreshToken });"),
        a('    expect(res.status).toBe(200);'),
        a("    expect(res.body.accessToken).not.toEqual(accessToken);"),
        a("    expect(res.body.refreshToken).not.toEqual(refreshToken);"),
        a('    refreshToken = res.body.refreshToken;'),
        a('  });'),
        a(''),
        a("  it('POST /auth/refresh rejects replayed token (family rotation)', async () => {"),
        a('    const oldToken = refreshToken;'),
        a("    await request(app).post('/auth/refresh').send({ refreshToken: oldToken });"),
        a("    const res = await request(app).post('/auth/refresh').send({ refreshToken: oldToken });"),
        a('    expect(res.status).toBe(401);'),
        a("    expect(res.body.error).toBe('INVALID_REFRESH_TOKEN');"),
        a('  });'),
        a(''),
        a("  it('GET /auth/sessions lists active sessions for the user', async () => {"),
        a("    const res = await request(app)"),
        a("      .get('/auth/sessions')"),
        a("      .set('Authorization', `Bearer ${accessToken}`);"),
        a('    expect(res.status).toBe(200);'),
        a("    expect(res.body.sessions).toBeInstanceOf(Array);"),
        a("    expect(res.body.sessions[0]).toHaveProperty('isCurrent', true);"),
        a('  });'),
        a('});'),
      ],
    },
  ],
};

const loginComponentTestDiff: FileDiff = {
  path: 'tests/login.component.test.tsx',
  additions: 71,
  deletions: 0,
  isNew: true,
  hunks: [
    {
      header: '@@ -0,0 +1,71 @@',
      lines: [
        a("import { render, screen, fireEvent, waitFor } from '@testing-library/react';"),
        a("import userEvent from '@testing-library/user-event';"),
        a("import { describe, it, expect, vi, beforeEach } from 'vitest';"),
        a("import { LoginForm } from '../src/components/auth/LoginForm';"),
        a(''),
        a("describe('LoginForm component', () => {"),
        a('  const mockOnSuccess = vi.fn();'),
        a(''),
        a("  beforeEach(() => { vi.clearAllMocks(); });"),
        a(''),
        a("  it('renders all form fields and the submit button', () => {"),
        a('    render(<LoginForm onSuccess={mockOnSuccess} />);'),
        a("    expect(screen.getByPlaceholderText(/email/i)).toBeInTheDocument();"),
        a("    expect(screen.getByPlaceholderText(/password/i)).toBeInTheDocument();"),
        a("    expect(screen.getByRole('button', { name: /sign in/i })).toBeInTheDocument();"),
        a("    expect(screen.getByText(/keep me signed in/i)).toBeInTheDocument();"),
        a('  });'),
        a(''),
        a("  it('shows loading spinner while authenticating', async () => {"),
        a("    vi.stubGlobal('fetch', () => new Promise(() => {})); // never resolves"),
        a('    render(<LoginForm onSuccess={mockOnSuccess} />);'),
        a("    await userEvent.type(screen.getByPlaceholderText(/email/i), 'user@test.com');"),
        a("    await userEvent.type(screen.getByPlaceholderText(/password/i), 'password123');"),
        a("    fireEvent.click(screen.getByRole('button', { name: /sign in/i }));"),
        a("    await waitFor(() => expect(screen.getByText(/authenticating/i)).toBeInTheDocument());"),
        a('  });'),
        a(''),
        a("  it('displays error banner on invalid credentials', async () => {"),
        a("    vi.stubGlobal('fetch', vi.fn().mockResolvedValue({"),
        a('      ok: false,'),
        a("      json: async () => ({ message: 'Authentication failed. Please try again.' }),"),
        a('    }));'),
        a('    render(<LoginForm onSuccess={mockOnSuccess} />);'),
        a("    await userEvent.type(screen.getByPlaceholderText(/email/i), 'bad@test.com');"),
        a("    await userEvent.type(screen.getByPlaceholderText(/password/i), 'wrongpass');"),
        a("    fireEvent.click(screen.getByRole('button', { name: /sign in/i }));"),
        a("    await waitFor(() =>"),
        a("      expect(screen.getByText(/authentication failed/i)).toBeInTheDocument()"),
        a('    );'),
        a("    expect(mockOnSuccess).not.toHaveBeenCalled();"),
        a('  });'),
        a('});'),
      ],
    },
  ],
};

// ── ASSEMBLED PR ANALYSIS ────────────────────────────────────────────────────

export const MOCK_PR: PRAnalysis = {
  prNumber: 247,
  title: 'feat(auth): Implement OAuth2 refresh tokens with persistent session tracking',
  repo: 'acme-corp / platform',
  branch: 'feat/oauth2-refresh-tokens',
  author: 'ai-agent-claude-v2',
  createdAt: '2024-06-15T09:23:44Z',
  executiveSummary:
    'This PR upgrades the authentication system from short-lived 7-day JWTs to a secure OAuth2 refresh token flow (30-day access / 90-day refresh), adds persistent session tracking in PostgreSQL with token-family rotation to prevent replay attacks, redesigns the login UI with modern loading/error states, and ships 165 lines of integration and component tests covering the new token lifecycle.',
  riskStatement:
    'Medium-high risk: auth changes affect all protected routes and require a one-time session migration for existing users — coordinate rollout with the DevOps team.',
  totalFiles: 10,
  totalAdditions: 518,
  totalDeletions: 52,
  splitBrainFiles: ['src/routes/auth.routes.ts'],
  clusters: [
    {
      id: 'auth-token-upgrade',
      emoji: '🔐',
      title: 'Upgrade Auth Token Expiry to 30 Days',
      description:
        'Extends JWT access tokens from 7 → 30 days, adds a secure refresh token system with 90-day validity and token-family rotation, and updates all middleware to handle token expiry gracefully with a structured REFRESH_REQUIRED error code.',
      risk: 'high',
      color: '#f87171',
      bgColor: 'rgba(239,68,68,0.08)',
      borderColor: 'rgba(239,68,68,0.25)',
      files: [
        { path: 'src/config/auth.config.ts', additions: 16, deletions: 4 },
        { path: 'src/middleware/authenticate.ts', additions: 38, deletions: 11 },
        { path: 'src/routes/auth.routes.ts', additions: 33, deletions: 5, isSplitBrain: true, hunkIndices: [0, 1] },
      ],
      status: 'pending',
      additions: 87,
      deletions: 20,
    },
    {
      id: 'login-ui-polish',
      emoji: '🎨',
      title: 'Polish Login UI & Component Styles',
      description:
        'Redesigns LoginForm with a modern layout, smooth fade-in animation, shake error states, a "Remember me" toggle, and loading indicator. Extends the Button component with 5 new variants (ghost, danger, success) plus small/large size props.',
      risk: 'low',
      color: '#c084fc',
      bgColor: 'rgba(192,132,252,0.08)',
      borderColor: 'rgba(192,132,252,0.25)',
      files: [
        { path: 'src/components/auth/LoginForm.tsx', additions: 67, deletions: 18 },
        { path: 'src/components/ui/Button.tsx', additions: 29, deletions: 7 },
        { path: 'src/styles/auth.module.css', additions: 42, deletions: 3 },
      ],
      status: 'pending',
      additions: 138,
      deletions: 28,
    },
    {
      id: 'session-persistence',
      emoji: '🗄️',
      title: 'Add Persistent Session Storage',
      description:
        'Creates a new user_sessions PostgreSQL table with proper composite indexes, a typed Session model with SHA-256 token hashing, and wires session creation/revocation into the auth routes. Supports multi-device management and full audit trail.',
      risk: 'medium',
      color: '#fbbf24',
      bgColor: 'rgba(251,191,36,0.08)',
      borderColor: 'rgba(251,191,36,0.25)',
      files: [
        { path: 'db/migrations/20240615_create_sessions.sql', additions: 26, deletions: 0, isNew: true },
        { path: 'src/models/Session.ts', additions: 72, deletions: 0, isNew: true },
        { path: 'src/routes/auth.routes.ts', additions: 30, deletions: 4, isSplitBrain: true, hunkIndices: [2, 3] },
      ],
      status: 'pending',
      additions: 128,
      deletions: 4,
    },
    {
      id: 'auth-test-coverage',
      emoji: '🧪',
      title: 'Add Integration Tests for Auth Flow',
      description:
        'Ships 165 lines of Vitest tests: integration tests cover the full refresh token lifecycle including replay-attack detection via token-family rotation; component tests cover LoginForm rendering, loading state, and error banner behavior.',
      risk: 'low',
      color: '#34d399',
      bgColor: 'rgba(52,211,153,0.08)',
      borderColor: 'rgba(52,211,153,0.25)',
      files: [
        { path: 'tests/auth.integration.test.ts', additions: 94, deletions: 0, isNew: true },
        { path: 'tests/login.component.test.tsx', additions: 71, deletions: 0, isNew: true },
      ],
      status: 'pending',
      additions: 165,
      deletions: 0,
    },
  ],
  fileDiffs: {
    'src/config/auth.config.ts': authConfigDiff,
    'src/middleware/authenticate.ts': middlewareDiff,
    'src/routes/auth.routes.ts': authRoutesDiff,
    'src/components/auth/LoginForm.tsx': loginFormDiff,
    'src/components/ui/Button.tsx': buttonDiff,
    'src/styles/auth.module.css': authCssDiff,
    'db/migrations/20240615_create_sessions.sql': sessionMigrationDiff,
    'src/models/Session.ts': sessionModelDiff,
    'tests/auth.integration.test.ts': authTestDiff,
    'tests/login.component.test.tsx': loginComponentTestDiff,
  },
};

export const SAMPLE_DIFF_TEXT = `diff --git a/src/config/auth.config.ts b/src/config/auth.config.ts
index 4f8a92c..d7e1034 100644
--- a/src/config/auth.config.ts
+++ b/src/config/auth.config.ts
@@ -1,14 +1,26 @@
 import { SignOptions } from 'jsonwebtoken';

 export const AUTH_CONFIG = {
-  accessTokenSecret: process.env.JWT_SECRET!,
-  accessTokenExpiry: '7d',
+  accessTokenSecret: process.env.JWT_ACCESS_SECRET!,
+  refreshTokenSecret: process.env.JWT_REFRESH_SECRET!,
+  accessTokenExpiry: '30d',
+  refreshTokenExpiry: '90d',
   algorithm: 'HS256' as SignOptions['algorithm'],
 };

diff --git a/src/middleware/authenticate.ts b/src/middleware/authenticate.ts
index a23bc14..f948210 100644
--- a/src/middleware/authenticate.ts
+++ b/src/middleware/authenticate.ts
@@ -1,8 +1,10 @@
 import { Request, Response, NextFunction } from 'express';
-import jwt from 'jsonwebtoken';
+import jwt, { TokenExpiredError } from 'jsonwebtoken';
 import { AUTH_CONFIG } from '../config/auth.config';

diff --git a/src/routes/auth.routes.ts b/src/routes/auth.routes.ts
index 8bc9301..c2a7f44 100644
--- a/src/routes/auth.routes.ts
+++ b/src/routes/auth.routes.ts
@@ -28,12 +31,35 @@
-  const token = generateToken({ sub: user.id });
+  const { accessToken, refreshToken, expiresIn } = await generateTokenPair(user.id);
+
+router.post('/refresh', async (req, res) => {
+  const tokens = await rotateRefreshToken(refreshToken);
+  res.json(tokens);

diff --git a/src/components/auth/LoginForm.tsx b/src/components/auth/LoginForm.tsx
diff --git a/src/components/ui/Button.tsx b/src/components/ui/Button.tsx
diff --git a/src/styles/auth.module.css b/src/styles/auth.module.css
diff --git a/db/migrations/20240615_create_sessions.sql b/db/migrations/20240615_create_sessions.sql
new file mode 100644
diff --git a/src/models/Session.ts b/src/models/Session.ts
new file mode 100644
diff --git a/tests/auth.integration.test.ts b/tests/auth.integration.test.ts
new file mode 100644
diff --git a/tests/login.component.test.tsx b/tests/login.component.test.tsx
new file mode 100644`;
